excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://cleder.github.io
title: Christian Ledermann
tagline: Open Source Software and Open Data
description: My awesome new site
paginate: 5